
export { ExtendedText } from './src/main/ets/components/Text'

export *  from './src/main/ets/TextOverflowWidget'
export *  from './src/main/ets/builder/WidgetBuilder'
export *  from './src/main/ets/painting/InlineSpan'
export *  from './src/main/ets/painting/PlaceholderSpan'
export *  from './src/main/ets/painting/TextSpan'
export *  from './src/main/ets/painting/WidgetSpan'
export *  from './src/main/ets/builder/SpecialTextSpanBuilder'
export *  from './src/main/ets/Utils'